name: Lint and Test

on:
  workflow_dispatch:
  push:

jobs:
  black:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./budget-app
    steps:
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Linting-black
        run: poetry run black . --check
  
  isort:
    needs: black
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./budget-app
    steps:
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Linting-isort
        run: poetry run isort --profile black . --check
  


  pylint:
    needs: isort
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./budget-app
    steps:
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Linting-Pylint
        run: poetry run pylint $(git ls-files '*.py')

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./budget-app
    steps:
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # Run script
      - name: Testing
        run: poetry run pytest -s

