name: Lint and Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./budget-app
    steps:
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # Run script
      - name: Linting-Black
        run: poetry run black . --check

      - name: Linting-Isort
        run: poetry run isort . --check

      - name: Linting-Pylint
        run: poetry run pylint $(git ls-files '*.py')

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./budget-app
    steps:
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd budget-app/
          poetry install

      # Run script
      - name: Testing
        run: poetry run pytest -s

